get:
  tags:
    - Product
  summary: Get product by ID
  description: Returns a single product
  operationId: getProductById
  parameters:
    - name: product_id
      in: path
      description: ID of a product to return
      required: true
      schema:
        type: integer
        format: uuid
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/product/product.yaml'
    '400':
      description: Invalid ID supplied
    '404':
      description: Product not found
    '405':
      description: Invalid input
