get:
  tags:
    - Products
  summary: Get all products
  description: Returns all products from the system that the user has access to.
  operationId: listProducts
  responses:
    '200':
      description: A list of products.
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/v1/product/product-list.yaml"
    '404':
      description: No customers found
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/Problem.yaml"